# Can override default values in the default yaml
# Or add values which will then be merged with defaults
# Or have it specific for the development environment
db:
  host: 'localhost'
  username: 'postgres'
  password: 'postgres'
  synchronize: true # not recommended in production
jwt:
  secret: 'exampleSecret'